SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM (SELECT USER_ID, PRODUCT_ID,SALES_AMOUNT,SALES_DATE
FROM ONLINE_SALE
UNION ALL
SELECT NULL AS USER_ID, PRODUCT_ID,SALES_AMOUNT,SALES_DATE
FROM OFFLINE_SALE) T
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '3' 
ORDER BY 1,2,3 IS NULL ,3