SELECT T.HISTORY_ID,IF(P.DISCOUNT_RATE IS NULL, FEE, FEE * (100-P.DISCOUNT_RATE)/100) AS FEE
FROM (SELECT D.DURATION_TYPE,D.DIFF*C.DAILY_FEE AS FEE ,D.HISTORY_ID,C.CAR_TYPE
FROM (SELECT CAR_ID, DATEDIFF(END_DATE,START_DATE) +1 AS DIFF,HISTORY_ID,
CASE WHEN  DATEDIFF(END_DATE,START_DATE) +1 >=90 THEN 90
WHEN  DATEDIFF(END_DATE,START_DATE) +1>=30 THEN 30
WHEN  DATEDIFF(END_DATE,START_DATE) +1>=7 THEN 7
ELSE 0
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) D
JOIN CAR_RENTAL_COMPANY_CAR C
ON C.CAR_ID = D.CAR_ID) T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE LIKE CONCAT('',T.DURATION_TYPE,'%')
WHERE T.CAR_TYPE = '트럭'
ORDER BY FEE DESC, T.HISTORY_ID DESC