SELECT S.SCORE,E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
FROM HR_EMPLOYEES E JOIN (SELECT EMP_NO,SUM(SCORE) SCORE
FROM HR_GRADE
WHERE YEAR =2022 
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1) S
ON E.EMP_NO = S.EMP_NO